name: Deploy to Strato

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node einrichten
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Projekt bauen
        run: npm run build

      - name: Upload via SFTP
        uses: wangyucode/sftp-upload-action@v3
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: './dist'
          remoteDir: '/web'
